package org.ibase4j.model.generator;

import java.util.Date;
import org.ibase4j.core.base.BaseModel;

@SuppressWarnings("serial")
public class PbPublishment extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.PUBLISH_TYPE
     *
     * @mbggenerated
     */
    private String publishType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.FILES
     *
     * @mbggenerated
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.FILENAMES
     *
     * @mbggenerated
     */
    private String filenames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.PUBLISH_BY
     *
     * @mbggenerated
     */
    private String publishBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.PUBLISH_TIME
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_PUBLISHMENT.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.PUBLISH_TYPE
     *
     * @return the value of PB_PUBLISHMENT.PUBLISH_TYPE
     *
     * @mbggenerated
     */
    public String getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.PUBLISH_TYPE
     *
     * @param publishType the value for PB_PUBLISHMENT.PUBLISH_TYPE
     *
     * @mbggenerated
     */
    public void setPublishType(String publishType) {
        this.publishType = publishType == null ? null : publishType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.TITLE
     *
     * @return the value of PB_PUBLISHMENT.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.TITLE
     *
     * @param title the value for PB_PUBLISHMENT.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.FILES
     *
     * @return the value of PB_PUBLISHMENT.FILES
     *
     * @mbggenerated
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.FILES
     *
     * @param files the value for PB_PUBLISHMENT.FILES
     *
     * @mbggenerated
     */
    public void setFiles(String files) {
        this.files = files == null ? null : files.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.FILENAMES
     *
     * @return the value of PB_PUBLISHMENT.FILENAMES
     *
     * @mbggenerated
     */
    public String getFilenames() {
        return filenames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.FILENAMES
     *
     * @param filenames the value for PB_PUBLISHMENT.FILENAMES
     *
     * @mbggenerated
     */
    public void setFilenames(String filenames) {
        this.filenames = filenames == null ? null : filenames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.STATUS
     *
     * @return the value of PB_PUBLISHMENT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.STATUS
     *
     * @param status the value for PB_PUBLISHMENT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.PUBLISH_BY
     *
     * @return the value of PB_PUBLISHMENT.PUBLISH_BY
     *
     * @mbggenerated
     */
    public String getPublishBy() {
        return publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.PUBLISH_BY
     *
     * @param publishBy the value for PB_PUBLISHMENT.PUBLISH_BY
     *
     * @mbggenerated
     */
    public void setPublishBy(String publishBy) {
        this.publishBy = publishBy == null ? null : publishBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.PUBLISH_TIME
     *
     * @return the value of PB_PUBLISHMENT.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.PUBLISH_TIME
     *
     * @param publishTime the value for PB_PUBLISHMENT.PUBLISH_TIME
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.REMARKS
     *
     * @return the value of PB_PUBLISHMENT.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.REMARKS
     *
     * @param remarks the value for PB_PUBLISHMENT.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.DEL_FLAG
     *
     * @return the value of PB_PUBLISHMENT.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.DEL_FLAG
     *
     * @param delFlag the value for PB_PUBLISHMENT.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_PUBLISHMENT.CONTENT
     *
     * @return the value of PB_PUBLISHMENT.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_PUBLISHMENT.CONTENT
     *
     * @param content the value for PB_PUBLISHMENT.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_PUBLISHMENT
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", publishType=").append(publishType);
        sb.append(", title=").append(title);
        sb.append(", files=").append(files);
        sb.append(", filenames=").append(filenames);
        sb.append(", status=").append(status);
        sb.append(", publishBy=").append(publishBy);
        sb.append(", publishTime=").append(publishTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_PUBLISHMENT
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PbPublishment other = (PbPublishment) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPublishType() == null ? other.getPublishType() == null : this.getPublishType().equals(other.getPublishType()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getFiles() == null ? other.getFiles() == null : this.getFiles().equals(other.getFiles()))
            && (this.getFilenames() == null ? other.getFilenames() == null : this.getFilenames().equals(other.getFilenames()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getPublishBy() == null ? other.getPublishBy() == null : this.getPublishBy().equals(other.getPublishBy()))
            && (this.getPublishTime() == null ? other.getPublishTime() == null : this.getPublishTime().equals(other.getPublishTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_PUBLISHMENT
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPublishType() == null) ? 0 : getPublishType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getFiles() == null) ? 0 : getFiles().hashCode());
        result = prime * result + ((getFilenames() == null) ? 0 : getFilenames().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getPublishBy() == null) ? 0 : getPublishBy().hashCode());
        result = prime * result + ((getPublishTime() == null) ? 0 : getPublishTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}